; Chrome > Firefox Redirector — конфиг
;
; Домены через запятую (без www, без пробелов):
domains=nexusmods.com, freetp.org, kinogomy.net
;
; Путь к Firefox:
firefox=C:\Program Files\Mozilla Firefox\firefox.exe
;
; Закрывать вкладку в Chrome после открытия в Firefox? (true/false)
close_tab=true
;
; Интервал проверки в миллисекундах
interval=500
